### ISSUE TITLE
Failed to call service script/heatermeter_set_alarms. Service not found.

### ISSUE THREAD

**Issue by spoetnik** [ledhed-jgh/HAHeaterMeter#2] opened 2021-12-31 16:09 UTC
First: Thanks for this integration!

Setting the alarms results in :: Failed to call service script/heatermeter_set_alarms. Service not found.

**Comment by ledhed-jgh** [comment] 2024-02-08 05:21
I can't reproduce this issue.
Closing.

**Closed as completed** 2024-02-08 05:22 UTC
